---
title: "index"
author: "RPM"
date: "November 30, 2017"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---
#rm(list=ls())

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Scatterplot

```{r scatterplot}
# data()
# ?mpg
#mpg
g <- ggplot(data = mpg, aes(x = displ, y = hwy))
g + geom_point()
```

### I need color!

```{r color}

g + geom_point(aes(color = class))
```
### Shapes
```{r shapes}
s <- ggplot(data = mpg, aes(x = displ, y = hwy, shape = class))
s + geom_point()

```

### Shape size
```{r `shapesize`}
ss <- ggplot(data = mpg, aes(x = cty, y = hwy, size = class, color=fl))
ss + geom_point(alpha=0.2) #opacity

```
### shape color
```{r `shape color`}
ss <- ggplot(data = mpg, aes(x = cty, y = hwy, size = class, color=fl))
ss + geom_point(alpha=0.2, color="blue") #opacity

```

### Geoms
```{r geoms} 
  ggplot(data=mpg,aes(x=displ, y=hwy)) +
    geom_point() +
   geom_smooth(aes(x=displ, y=hwy))
    
```
### Geoms
```{r geoms2} 
  ggplot(data=mpg,aes(x=cty, y=displ)) +
    geom_point(aes(size=class,color=hwy>20),alpha=0.2) +
    theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),panel.background =element_blank())+
   geom_smooth(aes(x=cty, y=displ)) +
  geom_smooth(method="lm")
    
```

## Data Wrangling with `dplyr`

```{r datawrangline}
gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

## useful functions to get to know your data:
head(gapminder) #show 6 rows of data
tail(gapminder) #last six rows

head(gapminder,30)
tail(gapminder,9)

str(gapminder) #structure
names(gapminder) #col headers
d <- dim(gapminder) #dimension
ncol(gapminder)
nrow(gapminder)
c(nrow(gapminder), ncol(gapminder)) #c=combine function

summary(gapminder) #statistics

## everything above we operated on the whole gapminder dataset

head(gapminder$lifeExp)



```

`read_csv` is from the `readr` package (part of tidyverse). 
```{r dplyrr}
## Working with `dplyr`

filter(gapminder, lifeExp < 29)

filter(gapminder, country=="Mexico")

sw=filter(gapminder, country=="Sweden")
sw_mean=mean(sw$lifeExp)

mean(filter(gapminder, country=="Sweden")$lifeExp)

## pipe operator `%>%`
gapminder %>% head()

#data classes, re: mean produces a data vector/value ; tidyverse expects a dataframe
# so we need to use summarize

gapminder %>% 
  filter(country == "Sweden") %>% 
  summarize(mean_lifeExp = mean(lifeExp))



```

```{r more gapminder}

## select 2 columns
select(gapminder, year, lifeExp)

##using pipes
gapminder %>% 
  select(year, lifeExp) %>%
  tail()

## combine what we've learned
gapminder %>%
  filter(country == "Cambodia") %>%
  select(country, year,pop,gdpPercap)

# use select with minus sign
gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)

## a few more things with filter
gapminder %>%
  filter(country == "Mexico", year == 2002)

##`mutate()` to add columns
gapminder %>%
  mutate(gdp=pop*gdpPercap)

#let's add an index
gapminder %>%
  mutate(index=1:nrow(gapminder)) %>%
  tail()

#let's do both
test <- gapminder %>%
  mutate(gdp=pop*gdpPercap,index=1:nrow(gapminder)) %>%
  tail()

gapminder %>%
  filter(country %in% c("Egypt","Vietnam")) %>%
  mutate(maxgdp=max(gdpPercap))
  

## group_by() so we get two maxes!
gapminder %>%
  filter(country %in% c("Egypt","Vietnam")) %>%
  group_by(country) %>%
  summarize(max_gdpPercap=max(gdpPercap)) 

gapminder %>%
  group_by(country) %>%
  mutate(min_lifeExp=min(lifeExp),max(lifeExp)) %>%
  filter(min_lifeExp==lifeExp) %>%
  arrange(min_lifeExp)



```
###Joining datasets
```{r co2}
## read in the data. (same URL as yesterday, just with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore
co2 %>% head()
co2 %>% str()
co2 %>% dim() # 12

## create new variable that is only 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007) 
gap_2007 %>% dim() # 142  

## left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")

## explore
lj %>% dim() #142
lj %>% summary() # lots of NAs in the co2_2017 columm
#lj %>% View() 

## right_join gap_2007 and co2
rj <- right_join(gap_2007, co2)
rj <- right_join(gap_2007, co2, by = "country")

## explore
rj %>% dim() # 12
rj %>% summary()
#rj %>% View()



```

## tidyr Data formats

```{r data formats}
### Example dataset
#AirPassengers

#mpg #long format

## wide format year col removed
gap_wide <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv')
## yesterday's format (intermediate)
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#gather wide to slim key=name of new col and value=data
#spread slim to wide

gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values)

str(gap_long)
head(gap_long)
tail(gap_long)

gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values,
         dplyr::starts_with('pop'),
         dplyr::starts_with('lifeExp'),
         dplyr::starts_with('gdpPercap'))  #here i'm listing all the columns to use in gather

str(gap_long)
head(gap_long)
tail(gap_long)

### Or ignore columns so you don't have to type out all columns

gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values,
         -continent, -country)

str(gap_long)
head(gap_long)
tail(gap_long)

### `separate`out the years
gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values,
         -continent, -country) %>%
  separate(obstype_year,
           into = c('obs_type','year'),
           sep = "_",
           convert = T) #this ensures that the year column is an integer rather than a character

str(gap_long)
head(gap_long)
tail(gap_long)



```



```{r ggplot with formats}


life_df <- gap_long %>%
  filter(obs_type == "lifeExp",
         continent == "Americas")

p <- ggplot(life_df, aes(x = year, y = obs_values, color = country)) +
  geom_line()

tests <- gap_long %>% group_by(continent, year, obs_type) %>% 
  summarize(means = mean(obs_values)) %>% 
  filter(obs_type == "lifeExp", year %in% c(seq(1982,2007)))

pp <-  ggplot(tests, aes(x = year, y = means, color = continent)) +
  geom_line() +
  labs(title='Mean life expectancy per continent',
       x='Year',
       y='Age (years)',
  color='Continent')
#View(pp)
pp





```

```{r spread}
## `spread`
gap_normal <- gap_long %>% 
  spread(key=obs_type, 
         value=obs_values)
 

dim(gap_normal)
dim(gapminder)
names(gap_normal)
names(gapminder)

### Exercise convert gap_long back to gap_wide

tail(gap_long)

gap_wide_new <- unite(gap_long, "var_name",c("obs_type","year")) %>% 
  spread(key=var_name,
         value=obs_values)

names(gap_wide_new)

```

